version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  alunoswebapi:
    image: alunoswebapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=aluno;username=postgres;password=12345"
    networks:
      - dockerapi-dev

  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "aluno"
    networks:
      - dockerapi-dev
volumes:
  db-data:
